version: '2'
services:
  frontend:
    image: semtech/ember-proxy-service:1.1.0
    volumes:
      - ./dist:/app
    links:
      - identifier:backend
    environment:
      VIRTUAL_HOST: "barbecue.bravoer.be"
      LETSENCRYPT_HOST: "barbecue.bravoer.be"
      LETSENCRYPT_EMAIL: "erika.pauwels@gmail.com"
      STATIC_FOLDERS_REGEX: "^/(assets|export)/"
  identifier:
    image: semtech/mu-identifier:1.2.0
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:1.1.0
    links:
      - resources:resources
      - export:export
    volumes:
      - ./backend/dispatcher:/config
  resources:
    image: semtech/mu-cl-resources:1.15.0
    links:
      - db:database
    volumes:
      - ./backend/resources:/config
  export:
    image: semtech/mu-export-js-template:0.2.0
    volumes:
      - ./backend/export:/config
    links:
      - db:database
  db:
    image: tenforce/virtuoso:1.1.0-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
    volumes:
      - ./backend/db:/data
